### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by onlyjob** [pborman/uuid#11]
Please consider assigning version numbers and tagging releases. Tags/releases
are quite useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Thank you.

**Comment by pborman** [comment]
I have added release tags.  Currently marked as preliminary.

**Comment by onlyjob** [comment]
Thank you. :-)
