### ISSUE TITLE
Invalid UUID format with Postgres

### ISSUE THREAD

**Issue by dre1080** [pborman/uuid#12]
I get a "Scan: invalid UUID format" when using with PostgreSQL. Seems that it parses ok but, when checking the variant of the UUID, if the length is more than 16 bytes then it's considered invalid. However, Postgres returns a UUID of length 36 (32 hex + 4 dashes) with `uuid_generate_v4()` function from `uuid-ossp` extension in accordance with Section 3 of [RFC4122](http://www.ietf.org/rfc/rfc4122.txt).

**Comment by jboverfelt** [comment]
So this has to do with the interplay of the uuid extension you're using for Postgres, this library, and whatever Postgres driver you're using (assuming lib/pq). The code in sql.go assumes that if a byte slice comes back, then it's in the compact version (no dashes, 16 bytes). It appears that however the uuid extension stores the uuid, lib/pq is interpreting it as a []byte when decoding it. If your uuid was coming out of the database as a string, then it would work. 

I suppose a solution would be adding a special case to check if the byte slice is longer than 16 bytes and then running Parse on it and returning that, similar to how it's done in [this library](https://github.com/satori/go.uuid/blob/master/uuid.go#L286). @pborman I'm willing to submit another pull request add this behavior if you want.

**Comment by jboverfelt** [comment]
Though, in general, supporting all the possible combinations of uuid generation + database + database driver will be difficult. It's always possible for users that can't use the default behavior to wrap in their own UUID type and define a Scan method on that to override the behavior. It's more boilerplate but will prevent the code in this implementation of Scan from getting out of control.

**Comment by pborman** [comment]
I think checking for a length of 16 in scan seems reasonable.  If the length is exactly 16 then assume it is a binary UUID, otherwise it must be parsed.  Feel free to add a pull request for this.

**Comment by jboverfelt** [comment]
Alright I'll get to that this week.
