### ISSUE TITLE
Contributors need to sign the CLA

### ISSUE THREAD

**Issue by pborman** [pborman/uuid#26]
I was informed by our legal counsel that, just like the Go project, contributors to the uuid package must sign the Google CLA.  It was my mistake for not requesting this before accepting any pull requests.  I am sorry about that.  Basically, the CLA gives Google the right to redistribute the code you have contributed to any Google open source project (because I work for Google, my projects automatically fall under this category).  On the plus side, the CLA specifically states your contribution is AS IS and you are under no obligation to support the code :-)

The CLA is at [https://cla.developers.google.com/clas](https://cla.developers.google.com/clas)

Please let me know when you have signed the CLA.  Thank you for your understanding.

    -Paul

Contributors: @bmatsuo @shawnps @theory @jboverfelt @cd1 @dansouza @wallclockbuilder

**Comment by jboverfelt** [comment]
Done.

**Comment by dansouza** [comment]
"Thanks, your CLA has been submitted."

**Comment by theory** [comment]
> Thanks, your CLA has been submitted.

**Comment by bmatsuo** [comment]
Done :)

**Comment by cd1** [comment]
done

**Comment by shawnps** [comment]
@pborman I believe I've signed already for contributions to Go, is this separate? I see a Google CLA on file from Aug 2012.

**Comment by pborman** [comment]
@shawnps Nope, same one, you are fine then.  Thanks for letting me know!

**Comment by wallclockbuilder** [comment]
@pborman I think I've already signed the Google CLA while contributing to another Google open source project. I'll take a closer look at this after work.

**Comment by pborman** [comment]
Thanks everyone!
