### ISSUE TITLE
New UUID type optimized for DB indexing

### ISSUE THREAD

**Issue by dansouza** [pborman/uuid#37]
I'm considering adding a second type of UUID to the package that, when used with databases (sql.go), makes it easier to work with UUID values as indexed values by observing the best practices described at [Storing UUID Values in MySQL Tables](http://mysqlserverteam.com/storing-uuid-values-in-mysql-tables/) when it comes to encoding the UUID into a binary form (for better indexing). Alternatively just the `uuid.Parse() `and `uuid.String()` functions could be changed to manipulate the internal binary representation of the `uuid`, but this might break some cases where people rely on the internal representation to be a standard UUIDv1. I still need to plan the details on how to implement this optimally, but wanted to ask first: would this new type be welcomed into this package?

Ideally this should shit on the DB side of things (with a proper UUID data type, I think pgsql does that) but MySQL/MariaDB/Percona lacks it, so having the client-side do these conversions magically would help by making things work transparently.

**Comment by pborman** [comment]
I don't think a new UUID type unique to this package would be a good idea.  That said, there is nothing preventing a client from generating it's own set of bits and then just setting the version and variant fields:

```
        uuid[6] = (uuid[6] & 0x0f) | 0x40 // Version 4
        uuid[8] = (uuid[8] & 0x3f) | 0x80 // Variant is 10

```

Most code probably doesn't care about the Version and Variant, but see [rfc4122](https://www.ietf.org/rfc/rfc4122.txt).

If the SQL community agreed on a specific format for SQL, that should be considered.

**Comment by pborman** [comment]
I am closing this issue as this functionality can easily be added externally by generating a the 16 bytes, put them in a slice, and then type castingh:

```
slice := makeMy16ByteSliceWithMyAlgorithm()
id := uuid.UUID(slice)
```

Please reopen or file a new issue if there is a standard SQL UUID format.
