### ISSUE TITLE
Error trying to install

### ISSUE THREAD

**Issue by MBonell** [pborman/uuid#38]
`$ go get github.com/pborman/uuid`

`can't load package: package github.com/pborman/uuid: no buildable Go source files in MY_WORSKPACE/src/github.com/pborman/uuid`

**Comment by pborman** [comment]
It think this is a local error.  From your source directory you should see something like:
```
$ ls github.com/pborman/uuid
CONTRIBUTING.md	dce.go		marshal_test.go	sql_test.go	uuid_test.go
CONTRIBUTORS	doc.go		node.go		time.go		version1.go
LICENSE		hash.go		seq_test.go	util.go		version4.go
README.md	marshal.go	sql.go		uuid.go
```
I am unable to reproduce this error.
