### ISSUE TITLE
would be cool to continue to use releases and semantic versioning

### ISSUE THREAD

**Issue by dfuentes77** [pborman/uuid#39]
This is so that when using a dependency manager, we can lock to a version and get predictable builds

Otherwise, we're sticking to a commit sha or always pulling master.

For example, using [glide](http://glide.sh/), we can set it to only pull certain patch/minor versions based on our comfort.

**Comment by pborman** [comment]
There has been a non-production v1.0 release.  Today I marked the current master as v1.1, so you should be able to use that.   Hopefully this addresses your concerns.

Thank you for the comment!

**Comment by dfuentes77** [comment]
Awesome, thanks!
