### ISSUE TITLE
"syntax error: unexpected ="

### ISSUE THREAD

**Issue by Mebus** [pborman/uuid#56]
Hallo,

unfortunately I cannot install this:

<code>
% go get github.com/pborman/uuid                                                                                                                                                                                            
# github.com/pborman/uuid
go/src/github.com/pborman/uuid/time.go:15: syntax error: unexpected =
</code>

Mebus

**Comment by pborman** [comment]
What version of Go are you using?

**Comment by Mebus** [comment]
```
go version go1.4 linux/amd64
```

Mebus

**Comment by Mebus** [comment]
ah, damn. It's far too old.
