### ISSUE TITLE
Repo does not have a test sticker

### ISSUE THREAD

**Issue by wallclockbuilder** [pborman/uuid#9]
Looking at the repo, it is impossible to tell at a glance that the tests are passing.

**Comment by wallclockbuilder** [comment]
It will be helpful to have a sticker showing the automated CI results from travis.

**Comment by wallclockbuilder** [comment]
Here is a sample from the go postgres package repo:
![example-build-passing](https://cloud.githubusercontent.com/assets/2033945/8747506/548bb128-2c83-11e5-8e0e-6ab17aa4939d.png)

**Comment by pborman** [comment]
Thanks, I have configured travis-ci and included the sticker in README.md.
